site_name: HUG Documentation
site_description: High-Altitude Universal Gondola Platform
site_author: Balloon Section WUT

theme:
  name: material
  palette:
    scheme: slate

nav:
  - Home: index.md

  - Mission:
      - CONOPS: mission/conops.md

  - Architecture:
      - Platform Architecture: architecture/platform-architecture.md

  - Requirements:
      - Overview: requirements/overview.md

  - Interfaces:
      - Payload Interface: interfaces/payload-interface.md
      - Electrical Interface: interfaces/electrical-interface.md
      - Communication Interface: interfaces/communication-interface.md
      - Mechanical Interface: interfaces/mechanical-interface.md

  - Operations:
      - Launch Operations: operations/launch-operations.md
      - Recovery Operations: operations/recovery-operations.md
      - Ground Segment: operations/ground-segment.md